Repository pactus-project/PIPs, pull requests merged in 2023-12, with the labels that each got.

#57 updating pip-8
  PIPs/pip-8.md
  assets/pip-8/pip-8-address.png
Labels: c-update, s-final, t-core

#59 updating pip-2
  PIPs/pip-2.md
Labels: c-update, s-accepted

#60 updating pip-2
  PIPs/pip-2.md
  assets/pip-2/locktime-ttl.png
Labels: c-update, s-accepted

#61 updating pip-3
  PIPs/pip-2.md
  PIPs/pip-3.md
Labels: c-update, s-accepted

#62 updating pip-7
  PIPs/pip-2.md
  PIPs/pip-7.md
Labels: s-draft, c-update, t-networking, s-accepted

#63 updating pip-13
  PIPs/pip-13.md
Labels: s-draft, c-update, t-core

#64 adding pip-15
  PIPs/pip-15.md
Labels: s-draft, c-new

#67 accepted pip-10
  PIPs/pip-10.md
Labels: c-status, s-accepted, t-core

#68 chore: update pip-13 status
  PIPs/pip-13.md
Labels: s-final, c-status, t-core

#70 Removing Ethereum related names in template and PIP-1
  PIPs/pip-1.md
  pip-template.md
Labels: t-process, s-draft, c-update

#71 Adding PIP-16 adding event to transactions
  PIPs/pip-16.md
Labels: s-draft, c-new, t-core

#74 Fixing PIP-17 yaml headers issue
  PIPs/pip-17.md
Labels: s-draft, c-new, t-core

#77 Update pip-17 adding more details
  PIPs/pip-17.md
Labels: s-draft, c-update, t-core

#78 Time Check Proposal
  PIPs/pip-18.md
Labels: s-draft, c-new, t-core

#80 updating pip-15
  PIPs/pip-15.md
Labels: s-draft, c-update, t-interface
