Repository pactus-project/PIPs, pull requests merged in 2023-09, with the labels that each got.

#5 Adding pip-0003, removing sequence from transaction
  PIPs/pip-0003.md
Labels: w-ci, c-new, s-final

#8 Adding pip-0004, Indexing Public Keys
  PIPs/pip-0004.md
  assets/pip-0004/indexed-public-key.png
Labels: c-new, s-final

#4 Adding pip-0002, for lock-time transactions
  PIPs/pip-0002.md
Labels: w-ci, c-new, s-final

#9 Adding pip-5, address prefix
  PIPs/pip-5.md
Labels: s-draft, c-new

#21 Adding pip-7, Checking Timestamp Difference in Handshaking
  PIPs/pip-7.md
Labels: s-draft, c-new, t-networking

#23 fix: <> instead of () for emails
  PIPs/pip-1.md
  PIPs/pip-4.md
  PIPs/pip-5.md
  PIPs/pip-6.md
Labels: t-process, s-draft, c-update, s-final

#26 chore: updating pip-7
  PIPs/pip-7.md
Labels: s-draft, c-update, t-networking

#25 Use Standards Track instead of Standard(s)
  PIPs/pip-3.md
  PIPs/pip-4.md
  PIPs/pip-5.md
  PIPs/pip-6.md
  PIPs/pip-7.md
Labels: s-draft, c-update, s-final, t-networking, s-accepted

#27 Adding pip-8, Add Address Usage Next to Encryption in Address Type
  PIPs/pip-8.md
  assets/pip-8/pactus_address.png
  assets/pip-8/pip-8-address.png
Labels: s-draft, c-new, t-core

#24 Change pip-5 status
  PIPs/pip-5.md
Labels: c-status, s-withdrawn

#29 Updating pip-8
  PIPs/pip-8.md
  assets/pip-8/pactus_address.png
  assets/pip-8/pip-8-address.png
Labels: s-draft, c-update, t-core

#31 feat: add pip-9
  PIPs/pip-9.md
Labels: w-ci, s-draft, c-new, t-core

#32 fix: requires number in pip-9
  PIPs/pip-9.md
  pip-template.md
Labels: t-process, s-draft, c-update, t-core

#30 updating pip-8 title
  PIPs/pip-8.md
Labels: s-draft, c-update, t-core

#35 adding pip-10
  PIPs/pip-10.md
  assets/pip-10/change_proposer_0.png
  assets/pip-10/change_proposer_1.png
  assets/pip-10/fast_agreement_path.png
  assets/pip-10/protocol_overview.png
Labels: s-draft, c-new

#37 updating pip-10
  PIPs/pip-10.md
  assets/pip-10/change_proposer_0.png
Labels: s-draft, c-update, t-core

#39 doc: accepted pip-8 and pip-9 base on review Dr Allahbakhsh
  PIPs/pip-8.md
  PIPs/pip-9.md
Labels: c-status, s-accepted, t-core

#38 updating pip-8
  PIPs/pip-8.md
  assets/pip-8/pip-8-address.png
Labels: c-update, s-final, t-core

#40 introducing the pip-11
  PIPs/pip-11.md
  assets/pip-11/testvectors.py
  config/.markdownlint.yaml
Labels: s-draft, c-new, t-core

#43 updating the title
  PIPs/pip-11.md
Labels: s-draft, c-update, t-core

#44 Update pip-7, change time to 10 seconds
  PIPs/pip-7.md
Labels: s-draft, c-update, t-networking
