Repository pactus-project/PIPs, pull requests merged in 2023-11, with the labels that each got.

#46 pip-12: automated Version Updates and Announcements in GUI and Daemon Client
  PIPs/pip-12.md
Labels: s-draft, c-new, t-core

#52 pip-14: adding more details in agent hello and structured value
  PIPs/pip-14.md
  assets/pip-14/agent.png
Labels: c-new, s-accepted

#54 fix: add more detail to pip13 plus refrences
  PIPs/pip-13.md
Labels: s-draft, c-update, t-core

#55 feat: add extra detail to pip 13
  PIPs/pip-13.md
Labels: s-draft, c-update, t-core

#56 improve: agent value for add client standard details
  PIPs/pip-14.md
Labels: c-update, s-accepted
