Repository pactus-project/PIPs, pull requests merged in 2023-08, with the labels that each got.

#6 fix: replace pip with erc
  _includes/head.html
  _layouts/pip.html
  config/.jekyll-labels.yml
  config/pip-editors.yml
  pip-template.md
  rss/nonerc-last-call.xml
  rss/nonerc.xml
  rss/pip-last-call.xml
Labels: w-ci

#7 Revert "fix: replace pip with erc"
  _includes/head.html
  _layouts/pip.html
  config/.jekyll-labels.yml
  config/pip-editors.yml
  pip-template.md
  rss/nonerc-last-call.xml
  rss/nonerc.xml
  rss/pip-last-call.xml
Labels: w-ci, t-process, s-draft, c-update

#10 remove erc and fix workflow errors
  .github/workflows/ci.yml
  .gitignore
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/head.html
  _layouts/pip.html
  config/.jekyll-labels.yml
  config/pip-editors.yml
  pip-template.md
  rss/nonerc-last-call.xml
  rss/nonerc.xml
  rss/pip-last-call.xml
Labels: t-process, s-draft, c-update
