Repository pactus-project/PIPs, pull requests merged in 2024-06, with the labels that each got.

#116 pip-25: Dynamic fees structure
  PIPs/pip-25.md
Labels: w-ci, s-draft, c-new, t-core

#118 PIP-26: Minimum Availability Score
  PIPs/pip-26.md
Labels: s-draft, c-new, t-core

#121 PIP-26: Update the Minimum Availability Score
  PIPs/pip-26.md
  _config.yml
  _includes/head.html
Labels: s-draft, c-update, t-core

#122 PIP-19: update the displayMath
  Gemfile
  PIPs/pip-19.md
  _includes/head.html
Labels: c-update, s-final, t-core

#124 PIP-19: update the Minimum Score value
  PIPs/pip-26.md
Labels: s-draft, c-update, t-core

#125 fix linting issues and update some PIPs
  .editorconfig
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .github/workflows/jekyll-label-bot.yml
  PIPs/pip-1.md
  PIPs/pip-10.md
  PIPs/pip-11.md
  PIPs/pip-12.md
  PIPs/pip-13.md
  PIPs/pip-14.md
  PIPs/pip-15.md
  PIPs/pip-16.md
  PIPs/pip-17.md
  PIPs/pip-18.md
  PIPs/pip-19.md
  PIPs/pip-2.md
  PIPs/pip-20.md
  PIPs/pip-21.md
  PIPs/pip-22.md
  PIPs/pip-23.md
  PIPs/pip-24.md
  PIPs/pip-25.md
  PIPs/pip-26.md
  PIPs/pip-3.md
  PIPs/pip-4.md
  PIPs/pip-5.md
  PIPs/pip-6.md
  PIPs/pip-7.md
  PIPs/pip-8.md
  PIPs/pip-9.md
  _includes/head.html
  assets/css/style.scss
  assets/css/style2.scss
  config/.markdownlint.yaml
  config/.mdlrc.rb
  config/mlc_config.json
  pip-template.md
Labels: t-process, s-draft, c-update, s-final, t-networking, s-withdrawn, s-accepted, t-core, t-interface, s-rejected
