Repository pactus-project/PIPs, pull requests merged in 2024-03, with the labels that each got.

#96 chore: this pip accepted by core team
  PIPs/pip-20.md
Labels: c-status, s-accepted, t-interface

#97 chore: update pip status to final
  PIPs/pip-20.md
Labels: s-final, c-status, t-interface

#98 fix a typo and explain pair-slice
  PIPs/pip-15.md
Labels: c-update, s-final, t-interface

#99 update pip-19
  PIPs/pip-19.md
Labels: c-update, s-final, t-core
