Repository pactus-project/PIPs, pull requests merged in 2024-01, with the labels that each got.

#81 adding pip-19
  PIPs/pip-19.md
  assets/pip-19/validators_avalibility_testnet.png
Labels: s-draft, c-new, t-core

#83 updating pip-19
  PIPs/pip-19.md
Labels: s-draft, c-update, t-core

#84 chore: try fixing math issue (latex)
  PIPs/pip-19.md
  _config.yml
Labels: c-update, s-final, t-core

#85 updating pip-10
  PIPs/pip-10.md
Labels: c-update, s-accepted, t-core

#86 add: pip-20 authentication method
  PIPs/pip-20.md
Labels: s-draft, c-new, t-interface

#89 Updating PIP-17, removing unnecessary function for registrar contracts interface, fixing mistakes
  PIPs/pip-17.md
Labels: s-draft, c-update

#88 Create pip-21.md [unbond token can rebond at any time.]
  PIPs/pip-21.md
Labels: s-draft, c-new

#91 Added PIP22 to resolve client agent pattern in GUI for windows
  PIPs/pip-22.md
Labels: s-draft, c-new, t-interface
